In [18]:
#### Softmax classification ####

import tensorflow as tf

x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5],
             [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
            
    # 테스트(one-hot encoding)
    print('\n---------------- test1 ----------------')
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, " -> ", sess.run(tf.argmax(a, 1))) # argmax : 가장 큰 값의 index 반환
    
    print('\n---------------- test2 ----------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, " -> ", sess.run(tf.argmax(b, 1)))

    print('\n---------------- test3 ----------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, " -> ", sess.run(tf.argmax(c, 1)))

    print('\n---------------- test4 ----------------')
    all = sess.run(hypothesis, feed_dict={
                   X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, " -> ", sess.run(tf.argmax(all, 1)))

0 1.1394732
200 0.550836
400 0.44805205
600 0.37072587
800 0.29764614
1000 0.23823643
1200 0.21529178
1400 0.19635378
1600 0.18039285
1800 0.16675925
2000 0.1549838

---------------- test1 ----------------
[[2.4914981e-03 9.9749833e-01 1.0061518e-05]]  ->  [1]

---------------- test2 ----------------
[[0.9052905  0.08506272 0.00964677]]  ->  [0]

---------------- test3 ----------------
[[1.5342707e-08 3.5793739e-04 9.9964201e-01]]  ->  [2]

---------------- test4 ----------------
[[2.4914981e-03 9.9749833e-01 1.0061518e-05]
 [9.0529048e-01 8.5062720e-02 9.6467715e-03]
 [1.5342707e-08 3.5793739e-04 9.9964201e-01]]  ->  [1 0 2]
