In [1]:
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [2]:
## 배열, slicing ##

t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])# -1은 마지막 원소
print(t[2:5], t[4:-1]) # 2번부터 5번 전까지(slicing), 4번부터 마지막 전까지
print(t[:2], t[3:]) # 처음부터 2번까지, 3부터 마지막까지

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [4]:
## 2차원 배열 ##

t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [73]:
## Shape, Rank, Axis ##

t = tf.constant([1,2,3,4])
print("1\n", tf.shape(t).eval())

t = tf.constant([[1,2],
                 [3,4]])
print("2\n", tf.shape(t).eval())

t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
print("3\n", tf.shape(t).eval())

[ # axis = 0
    [ # axis = 1
        [ # axis = 2
            [1,2,3,4], # axis = 3
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

1
 [4]
2
 [2 2]
3
 [1 2 3 4]


[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

In [75]:
## Matmul, Multiply ##
# 행렬 곱셈

matrix1 = tf.constant([[3., 3.]]) # [1, 2]
matrix2 = tf.constant([[2.],[2.]]) # [2, 1]

print("1\n", tf.matmul(matrix1, matrix2).eval()) # [1, 1]

# 곱셈을 하지 않도록 주의!
# shape이 달라도 broadcasting으로 인해 곱셈이 됨.
print("2\n", (matrix1*matrix2).eval())

1
 [[12.]]
2
 [[6. 6.]
 [6. 6.]]


In [80]:
## Reduce mean ##
# 평균

print("1\n", tf.reduce_mean([1, 2], axis=0).eval())
# Integer의 평균 -> 정수 반환

x = [[1., 2.],
     [3., 4.]]

print("2\n", tf.reduce_mean(x).eval())
# axis를 쓰지 않으면 전체 원소의 평균

print("3\n", tf.reduce_mean(x, axis=0).eval())
# [1., 2.]와 [3., 4.]의 평균

print("4\n", tf.reduce_mean(x, axis=1).eval())
# [1., 2]의 평균, [3., 4.]의 평균

print("5\n", tf.reduce_mean(x, axis=-1).eval())
# axis=1과 같음

1
 1
2
 2.5
3
 [2. 3.]
4
 [1.5 3.5]
5
 [1.5 3.5]


In [83]:
## Reduce sum ##
# 합

x = [[1., 2.],
     [3., 4.]]

print("1\n", tf.reduce_sum(x).eval())

print("2\n", tf.reduce_sum(x, axis=0).eval())

print("3\n", tf.reduce_sum(x, axis=-1).eval())

print("4\n", tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval())
# 제일 안쪽 원소를 합한 뒤에 평균을 냄

1
 10.0
2
 [4. 6.]
3
 [3. 7.]
4
 5.0


In [84]:
## Argmax ##

x = [[0, 1, 2],
     [2, 1, 0]]

print("1\n", tf.argmax(x, axis=0).eval())

print("2\n", tf.argmax(x, axis=1).eval())

print("3\n", tf.argmax(x, axis=-1).eval())

1
 [1 0 0]
2
 [2 0]
3
 [2 0]


In [86]:
## Reshape** ##
# 원하는 형태로 변환

t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
print("1\n", t.shape)

print("2\n", tf.reshape(t, shape=[-1, 3]).eval()) # -1은 자동

print("3\n", tf.reshape(t, shape=[-1, 1, 3]).eval())

# Squeeze : 원소를 펴줌
print("4\n", tf.squeeze([[0], [1], [2]]).eval())

# Expand_dims : squeeze와 반대
print("5\n", tf.expand_dims([0, 1, 2], 1).eval())

1
 (2, 2, 3)
2
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
3
 [[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]
4
 [0 1 2]
5
 [[0]
 [1]
 [2]]


In [88]:
## One hot ##

print("1\n", tf.one_hot([[0], [1], [2], [0]], depth=3).eval())
# -> rank가 1 늘어남

# reshape을 통해 rank 줄이기
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
print("2\n", tf.reshape(t, shape=[-1, 3]).eval())

1
 [[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]]
2
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [90]:
## Casting ##
# 형변환

print("1\n", tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval())

print("2\n", tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval())

1
 [1 2 3 4]
2
 [1 0 1 0]


In [91]:
## Stack ##

x = [1, 4]
y = [2, 5]
z = [3, 6]

print("1\n", tf.stack([x, y, z]).eval())

print("2\n", tf.stack([x, y, z]).eval())

print("3\n", tf.stack([x, y, z], axis=1).eval())

1
 [[1 4]
 [2 5]
 [3 6]]
2
 [[1 4]
 [2 5]
 [3 6]]
3
 [[1 2 3]
 [4 5 6]]


In [95]:
## Ones like, Zeros like ##
# 같은 shape의 1, 0으로 채워진 행렬 생성

x = [[0, 1, 2],
     [2, 1, 0]]

print("1\n", tf.ones_like(x).eval())

print("2\n", tf.zeros_like(x).eval())

1
 [[1 1 1]
 [1 1 1]]
2
 [[0 0 0]
 [0 0 0]]


In [97]:
## Zip ##
# 여러 형렬을 한번에 처리가능

for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4
2 5
3 6
1 4 7
2 5 8
3 6 9
