In [19]:
## 특정 feature가 매우 큰 경우 regularization 사용 ##

import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

# regularization 함수 정의
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # 0으로 나누는 경우 방지
    return numerator / (denominator + 1e-7)

# 3행이 매우 큰 값, 마지막 행이 결과
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

# regularization 수행(각 열을 0 ~ 1로 표현)
# 하지 않으면 결과가 nan으로 나옴
xy = MinMaxScaler(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X: x_data, Y: y_data})
    print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
0 Cost: 0.34445655 
Prediction:
 [[0.2887479 ]
 [0.6597482 ]
 [0.7846861 ]
 [0.841248  ]
 [0.8418338 ]
 [0.79125696]
 [1.1515802 ]
 [0.91975707]]
1 Cost: 0.3116322 
Prediction:
 [[0.24310106]
 [0.58987105]
 [0.721828  ]
 [0.7862574 ]
 [0.7841002 ]
 [0.7332721 ]
 [1.0916067 ]
 [0.8530598 ]]
2 Cost: 0.2885759 
Prediction:
 [[0.22548342]
 [0.54823935]
 [0.6826236 ]
 [0.7497446 ]
 [0.74802506]
 [0.6962913 ]
 [1.0464361 ]
 [0.80124784]]
3 Cost: 0.26990658 
Prediction:
 [[0.224814  ]
 [0.52404654]
 [0.65805364]
 [0.72470665]
 [0.725334