In [17]:
import tensorflow as tf

# 3번의 시험 점수와 최종 점수 데이터(5명)
x1_data = [73., 93., 90., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1*w1 + x2*w2 + x3*w3 + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "\nCost:", cost_val, "\nPrediction:", hy_val, "\n")

0 
Cost: 55659.555 
Prediction: [-48.27724  -73.057594 -64.5608   -72.52973  -57.185642] 

10 
Cost: 39.53115 
Prediction: [160.15764 177.52225 183.22575 196.308   133.9569 ] 

20 
Cost: 38.835434 
Prediction: [160.75603 178.28638 183.96062 197.10555 134.54831] 

30 
Cost: 38.637146 
Prediction: [160.73367 178.30423 183.95755 197.10245 134.57048] 

40 
Cost: 38.439754 
Prediction: [160.70952 178.31984 183.95229 197.09698 134.59091] 

50 
Cost: 38.24349 
Prediction: [160.68544 178.33542 183.94704 197.09154 134.61127] 

60 
Cost: 38.0483 
Prediction: [160.66142 178.35094 183.94182 197.0861  134.63158] 

70 
Cost: 37.85402 
Prediction: [160.63744 178.36641 183.93658 197.08069 134.65182] 

80 
Cost: 37.660736 
Prediction: [160.61353 178.38184 183.93134 197.07527 134.67203] 

90 
Cost: 37.46862 
Prediction: [160.58969 178.39723 183.92616 197.06987 134.69217] 

100 
Cost: 37.27743 
Prediction: [160.56592 178.41258 183.92096 197.06448 134.71227] 

110 
Cost: 37.087288 
Prediction: [160.54222 

970 
Cost: 23.97343 
Prediction: [158.71904 179.60538 183.51665 196.65    136.27022] 

980 
Cost: 23.853235 
Prediction: [158.70015 179.61757 183.51251 196.64581 136.28609] 

990 
Cost: 23.733631 
Prediction: [158.68132 179.62971 183.50836 196.64162 136.30194] 

1000 
Cost: 23.614727 
Prediction: [158.66257 179.64185 183.50424 196.63745 136.31775] 

1010 
Cost: 23.496387 
Prediction: [158.64383 179.65395 183.50012 196.63329 136.3335 ] 

1020 
Cost: 23.378738 
Prediction: [158.62517 179.666   183.49603 196.62915 136.34923] 

1030 
Cost: 23.26156 
Prediction: [158.60652 179.67805 183.49193 196.62502 136.3649 ] 

1040 
Cost: 23.1451 
Prediction: [158.58792 179.69002 183.48782 196.62085 136.38052] 

1050 
Cost: 23.0293 
Prediction: [158.56941 179.702   183.48376 196.61674 136.39612] 

1060 
Cost: 22.914068 
Prediction: [158.55093 179.71393 183.47969 196.61266 136.41167] 

1070 
Cost: 22.79943 
Prediction: [158.5325  179.72585 183.47565 196.60854 136.42717] 

1080 
Cost: 22.685352 
Predicti

In [14]:
# Matrix 이용

import tensorflow as tf

x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], 
          [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.,], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "\nCost:", cost_val, "\nPrediction:\n", hy_val, "\n")

0 
Cost: 2891.175 
Prediction:
 [[102.9861  ]
 [127.94099 ]
 [124.15584 ]
 [133.67604 ]
 [ 99.633316]] 

10 
Cost: 0.9687721 
Prediction:
 [[150.54678]
 [185.0998 ]
 [180.47829]
 [195.00961]
 [143.22981]] 

20 
Cost: 0.9389981 
Prediction:
 [[150.69362]
 [185.27072]
 [180.64957]
 [195.19601]
 [143.35895]] 

30 
Cost: 0.9356886 
Prediction:
 [[150.69698]
 [185.2692 ]
 [180.65096]
 [195.19737]
 [143.35652]] 

40 
Cost: 0.9324004 
Prediction:
 [[150.69989]
 [185.26718]
 [180.65182]
 [195.19818]
 [143.35371]] 

50 
Cost: 0.9291359 
Prediction:
 [[150.70282]
 [185.2652 ]
 [180.65273]
 [195.199  ]
 [143.35094]] 

60 
Cost: 0.92587185 
Prediction:
 [[150.70572]
 [185.26317]
 [180.65356]
 [195.19981]
 [143.34814]] 

70 
Cost: 0.92265207 
Prediction:
 [[150.70862]
 [185.26115]
 [180.65443]
 [195.20059]
 [143.34538]] 

80 
Cost: 0.9194211 
Prediction:
 [[150.7115 ]
 [185.25916]
 [180.65527]
 [195.20139]
 [143.34259]] 

90 
Cost: 0.91623306 
Prediction:
 [[150.7144 ]
 [185.25719]
 [180.65617]
 [1

810 
Cost: 0.725251 
Prediction:
 [[150.9021 ]
 [185.12724]
 [180.71205]
 [195.25514]
 [143.15881]] 

820 
Cost: 0.72306794 
Prediction:
 [[150.90443]
 [185.1256 ]
 [180.71272]
 [195.25581]
 [143.15651]] 

830 
Cost: 0.7209083 
Prediction:
 [[150.90678]
 [185.12398]
 [180.71342]
 [195.25648]
 [143.15424]] 

840 
Cost: 0.7187593 
Prediction:
 [[150.90913]
 [185.12236]
 [180.71413]
 [195.25719]
 [143.152  ]] 

850 
Cost: 0.7166194 
Prediction:
 [[150.91145]
 [185.12073]
 [180.7148 ]
 [195.25784]
 [143.14972]] 

860 
Cost: 0.7144977 
Prediction:
 [[150.91377]
 [185.11913]
 [180.7155 ]
 [195.25851]
 [143.14746]] 

870 
Cost: 0.7123707 
Prediction:
 [[150.9161 ]
 [185.11752]
 [180.71619]
 [195.25919]
 [143.1452 ]] 

880 
Cost: 0.7102624 
Prediction:
 [[150.91841]
 [185.11592]
 [180.71687]
 [195.25986]
 [143.14294]] 

890 
Cost: 0.70818585 
Prediction:
 [[150.92072]
 [185.11433]
 [180.71756]
 [195.26051]
 [143.14073]] 

900 
Cost: 0.70610225 
Prediction:
 [[150.923  ]
 [185.11273]
 [180.7182

1820 
Cost: 0.55444086 
Prediction:
 [[151.10919]
 [184.98352]
 [180.77324]
 [195.31662]
 [142.95576]] 

1830 
Cost: 0.5531686 
Prediction:
 [[151.11098]
 [184.9823 ]
 [180.77377]
 [195.31715]
 [142.95403]] 

1840 
Cost: 0.55189615 
Prediction:
 [[151.1127 ]
 [184.98106]
 [180.77428]
 [195.3177 ]
 [142.95226]] 

1850 
Cost: 0.5506216 
Prediction:
 [[151.11449]
 [184.97984]
 [180.7748 ]
 [195.31825]
 [142.95052]] 

1860 
Cost: 0.54936004 
Prediction:
 [[151.11626]
 [184.9786 ]
 [180.77531]
 [195.31879]
 [142.94878]] 

1870 
Cost: 0.5481034 
Prediction:
 [[151.118  ]
 [184.9774 ]
 [180.77582]
 [195.31934]
 [142.94704]] 

1880 
Cost: 0.54685885 
Prediction:
 [[151.11974]
 [184.9762 ]
 [180.77634]
 [195.31987]
 [142.9453 ]] 

1890 
Cost: 0.5456288 
Prediction:
 [[151.12146]
 [184.97498]
 [180.77686]
 [195.3204 ]
 [142.94357]] 

1900 
Cost: 0.54437524 
Prediction:
 [[151.12323]
 [184.97377]
 [180.77736]
 [195.32094]
 [142.94183]] 

1910 
Cost: 0.54315305 
Prediction:
 [[151.12495]
 [184.972