In [11]:
## Learning rate의 변화에 따른 결과 ##

import tensorflow as tf
tf.set_random_seed(777)

# 학습 데이터와 테스트 데이터를 나눔.
x_date = [
    [1, 2, 1],
    [1, 3, 2],
    [1, 3, 4],
    [1, 5, 5],
    [1, 7, 5],
    [1, 2, 5],
    [1, 6, 6],
    [1, 7, 7]
]
y_date = [
    [0, 0, 1],
    [0, 0, 1],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 0],
    [0, 1, 0],
    [1, 0, 0],
    [1, 0, 0]
]
# 테스트 데이터
x_test = [
    [2, 1, 1],
    [3, 1, 2],
    [3, 3, 4]
]
y_test = [
    [0, 0, 1],
    [0, 0, 1],
    [0, 0, 1]
]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

# learning_rate를 1.5, 1e-10, 0.1로 바꿔가며 실행해 볼 것.
optimizer = tf.train.GradientDescentOptimizer(
    learning_rate=0.1).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                      feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        
    # 예측값
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    
    # 정확도 계산
    print("Accuracy:", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

    
# lr=1.5인 경우, 발산하여 결과가 nan으로 나옴.
# lr=1e-10인 경우, cost가 0에 가깝게 줄어들지 않음.
# lr=1.5인 경우, 결과가 정상적으로 나옴.

0 5.743528 [[-0.8496253  -1.0708807   1.4628384 ]
 [-1.3274658  -0.40155384 -0.47018272]
 [-0.04338787  0.33750522  0.15371704]]
1 2.8297276 [[-0.82502323 -1.0830983   1.450454  ]
 [-1.1658967  -0.46318936 -0.5701163 ]
 [ 0.11820507  0.28724754  0.0423818 ]]
2 2.03366 [[-0.8014895  -1.1046324   1.4484543 ]
 [-1.0072234  -0.57259786 -0.61938107]
 [ 0.27617592  0.18943264 -0.01777416]]
3 1.2997569 [[-0.7833722  -1.1130439   1.4387485 ]
 [-0.86817616 -0.61897993 -0.7120462 ]
 [ 0.41032833  0.15596089 -0.11845481]]
4 0.8929104 [[-0.78689986 -1.1178478   1.4470801 ]
 [-0.831934   -0.64740884 -0.71985954]
 [ 0.4350478   0.1446621  -0.13187549]]
5 0.88248265 [[-0.7993202  -1.115172    1.4568247 ]
 [-0.8429596  -0.63532436 -0.7209184 ]
 [ 0.41244698  0.17316864 -0.13778122]]
6 0.87540483 [[-0.8051803  -1.1194644   1.4669771 ]
 [-0.8198335  -0.65987056 -0.7194983 ]
 [ 0.4247247   0.16481407 -0.14170437]]
7 0.86887753 [[-0.8164427  -1.1178205   1.4765955 ]
 [-0.82618666 -0.6526427  -0.72037303]


161 0.60157216 [[-1.6786801  -1.2116805   2.4326935 ]
 [-0.5928792  -0.7864339  -0.81988865]
 [ 0.53268564  0.38054046 -0.46539128]]
162 0.6008255 [[-1.6828539  -1.2117088   2.4368956 ]
 [-0.5926611  -0.7861349  -0.82040566]
 [ 0.53411084  0.38043714 -0.4667132 ]]
163 0.60008293 [[-1.6870185  -1.211732    2.4410834 ]
 [-0.59244597 -0.7858369  -0.8209188 ]
 [ 0.53553504  0.38033238 -0.46803266]]
164 0.5993446 [[-1.6911738  -1.2117503   2.445257  ]
 [-0.5922337  -0.7855399  -0.821428  ]
 [ 0.5369583   0.38022617 -0.46934968]]
165 0.5986103 [[-1.69532    -1.2117636   2.4494164 ]
 [-0.59202445 -0.7852439  -0.82193327]
 [ 0.5383804   0.38011864 -0.4706643 ]]
166 0.59787977 [[-1.699457   -1.2117722   2.453562  ]
 [-0.5918179  -0.78494906 -0.82243466]
 [ 0.5398016   0.38000968 -0.4719765 ]]
167 0.5971534 [[-1.7035851  -1.2117759   2.4576938 ]
 [-0.59161425 -0.78465515 -0.82293224]
 [ 0.5412217   0.3798995  -0.47328633]]
168 0.59643084 [[-1.7077043  -1.2117748   2.461812  ]
 [-0.5914132  -0.78